version: '3.8'

services:
  posts:
    image: posts-service
    ports:
      - "4000:4000"

  comments:
    image: comments-service
    ports:
      - "4001:4001"

  event-bus:
    image: event-bus-service
    ports:
      - "4005:4005"
    depends_on:
      - posts
      - comments

  query:
    image: query-service
    ports:
      - "4002:4002"
    depends_on:
      - event-bus

  login:
    image: login-service
    ports:
      - "4006:4006"

  frontend:
    image: frontend-service
    ports:
      - "3000:3000"
